"""sync like table schema

Revision ID: 19ca27ec29f2
Revises: f7766b000533
Create Date: 2026-07-22 10:21:32.275877

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "19ca27ec29f2"
down_revision: Union[str, Sequence[str], None] = "f7766b000533"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_blogs_id"), table_name="blogs")
    op.alter_column(
        "likes", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.drop_index(op.f("ix_users_id"), table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.alter_column(
        "likes", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.create_index(op.f("ix_blogs_id"), "blogs", ["id"], unique=False)
    # ### end Alembic commands ###
