"""add citya and state field

Revision ID: 702dc140d817
Revises: c4bc293fbfbe
Create Date: 2026-07-15 15:02:00.533344

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "702dc140d817"
down_revision: Union[str, Sequence[str], None] = "c4bc293fbfbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("city", sa.String(), nullable=True))
    op.add_column("users", sa.Column("state", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "state")
    op.drop_column("users", "city")
    # ### end Alembic commands ###
