"""add ondelete cascade in blog talbe

Revision ID: aa65790bcf58
Revises: b11acb16d14a
Create Date: 2026-07-17 09:25:36.717990

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "aa65790bcf58"
down_revision: Union[str, Sequence[str], None] = "b11acb16d14a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("blogs_user_id_fkey"), "blogs", type_="foreignkey")
    op.create_foreign_key(
        None, "blogs", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "blogs", type_="foreignkey")
    op.create_foreign_key(
        op.f("blogs_user_id_fkey"), "blogs", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
