"""add otp,expire,verify fields in users model

Revision ID: b11acb16d14a
Revises: b2974018a3bd
Create Date: 2026-07-16 18:10:21.923588

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b11acb16d14a"
down_revision: Union[str, Sequence[str], None] = "b2974018a3bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("otp", sa.String(), nullable=True))
    op.add_column(
        "users", sa.Column("otp_expiry", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("users", sa.Column("otp_verified", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "otp_verified")
    op.drop_column("users", "otp_expiry")
    op.drop_column("users", "otp")
    # ### end Alembic commands ###
